name: wav2
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.9.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - cairo=1.18.4
  - colorama=0.4.6
  - comm=0.2.3
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - executing=2.2.1
  - expat=2.7.3
  - ffmpeg=7.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.15.0
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.14.1
  - fribidi=1.0.16
  - gdk-pixbuf=2.42.12
  - graphite2=1.3.14
  - harfbuzz=11.4.5
  - icu=75.1
  - ipykernel=6.31.0
  - ipython=8.30.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - lerc=4.0.0
  - libdeflate=1.22
  - libexpat=2.7.3
  - libffi=3.4.4
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libglib=2.84.4
  - libiconv=1.18
  - libintl=0.22.5
  - libjpeg-turbo=3.1.2
  - libopus=1.6
  - libpng=1.6.53
  - librsvg=2.58.4
  - libsodium=1.0.20
  - libtiff=4.7.0
  - libxml2=2.13.9
  - libzlib=1.3.1
  - matplotlib-inline=0.2.1
  - nest-asyncio=1.6.0
  - openh264=2.5.0
  - openssl=3.6.0
  - packaging=25.0
  - pango=1.56.4
  - parso=0.8.5
  - pcre2=10.46
  - pip=25.3
  - pixman=0.46.4
  - prompt-toolkit=3.0.52
  - prompt_toolkit=3.0.52
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.10.19
  - python-dateutil=2.9.0post0
  - pywin32=311
  - pyzmq=27.1.0
  - setuptools=80.9.0
  - six=1.17.0
  - sqlite=3.51.0
  - stack_data=0.6.3
  - svt-av1=2.3.0
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - ucrt=10.0.22621.0
  - vc=14.3
  - vc14_runtime=14.44.35208
  - vs2015_runtime=14.44.35208
  - wcwidth=0.2.13
  - wheel=0.45.1
  - x264=1!164.3095
  - x265=3.5
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.2
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - annotated-types==0.7.0
      - anyio==4.12.0
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.4.0
      - audioread==3.1.0
      - babel==2.17.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2025.11.12
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - datasets==4.4.1
      - defusedxml==0.7.1
      - dill==0.4.0
      - distro==1.9.0
      - exceptiongroup==1.3.1
      - fastapi==0.124.4
      - fastjsonschema==2.21.2
      - ffmpeg-python==0.2.0
      - filelock==3.20.0
      - fonttools==4.61.0
      - fqdn==1.5.1
      - frozenlist==1.8.0
      - fsspec==2025.10.0
      - future==1.0.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.36.0
      - idna==3.11
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jinja2==3.1.6
      - jiter==0.12.0
      - joblib==1.5.2
      - json5==0.12.1
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.0
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lazy-loader==0.4
      - librosa==0.11.0
      - llvmlite==0.46.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - mistune==3.1.4
      - mpmath==1.3.0
      - msgpack==1.1.2
      - multidict==6.7.0
      - multiprocess==0.70.18
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.4.2
      - notebook-shim==0.2.4
      - numba==0.63.1
      - numpy==2.2.6
      - openai==2.13.0
      - overrides==7.7.0
      - pandas==2.3.3
      - pandocfilters==1.5.1
      - pillow==11.3.0
      - platformdirs==4.5.1
      - pooch==1.8.2
      - prometheus-client==0.23.1
      - propcache==0.4.1
      - protobuf==6.33.2
      - pyarrow==22.0.0
      - pycparser==2.23
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydub==0.25.1
      - pyparsing==3.2.5
      - python-json-logger==4.0.0
      - python-multipart==0.0.21
      - pytz==2025.2
      - pywinpty==3.0.2
      - pyyaml==6.0.3
      - referencing==0.37.0
      - regex==2025.11.3
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - send2trash==1.8.3
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - starlette==0.50.0
      - sympy==1.14.0
      - terminado==0.18.1
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.1
      - tomli==2.3.0
      - torch==2.7.1+cu118
      - torchaudio==2.7.1+cu118
      - torchvision==0.22.1+cu118
      - tqdm==4.67.1
      - transformers==4.57.3
      - typing-inspection==0.4.2
      - tzdata==2025.2
      - uri-template==1.3.0
      - urllib3==2.6.2
      - uvicorn==0.38.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - xxhash==3.6.0
      - yarl==1.22.0
prefix: C:\Users\vipto\anaconda3\envs\wav2
